import re
import json
import sys


KNOWN_HEADINGS = {
    "FACTS": "Facts",
    "BRIEF FACTS": "Facts",
    "FACTUAL BACKGROUND": "Facts",
    "BACKGROUND": "Background",
    "ARGUMENTS": "Arguments",
    "SUBMISSIONS": "Submissions",
    "CONTENTIONS": "Contentions",
    "DISCUSSION": "Discussion",
    "FINDINGS": "Findings",
    "REASONS": "Reasons",
    "JUDGMENT": "Judgment",
    "ORDER": "Order",
    "OPERATIVE ORDER": "Order",
    "DIRECTIONS": "Directions",
    "CONCLUSION": "Conclusion",
}


ORDER_PHRASES = [
    "the petition is disposed",
    "the petition is allowed",
    "the petition is dismissed",
    "the appeal is allowed",
    "the appeal is dismissed",
    "the application is allowed",
    "the application is dismissed",
    "the present writ petition is disposed",
    "all the pending applications",
    "accordingly,",
]


def normalize_line(line):
    """
    Normalize whitespace without changing legal wording.
    """
    return re.sub(r"\s+", " ", line).strip()


def is_page_marker(line):
    """
    Detect page markers generated by the OCR pipeline.
    Example:
    ===== Page 1 =====
    """
    return bool(
        re.match(
            r"^=+\s*Page\s+\d+\s*=+$",
            line,
            re.IGNORECASE
        )
    )


def get_page_number(line):
    """
    Extract page number from an OCR page marker.
    """
    match = re.match(
        r"^=+\s*Page\s+(\d+)\s*=+$",
        line,
        re.IGNORECASE
    )

    if match:
        return int(match.group(1))

    return None


def is_numbered_paragraph(line):
    """
    Detect numbered legal paragraphs.

    Examples:
    1. Challenge...
    2. Learned counsel...
    10. The Court...
    """
    return bool(
        re.match(
            r"^\d{1,3}\.\s+",
            line
        )
    )


def get_paragraph_number(line):
    """
    Return paragraph number.
    """
    match = re.match(
        r"^(\d{1,3})\.\s+",
        line
    )

    if match:
        return int(match.group(1))

    return None


def remove_paragraph_number(line):
    """
    Remove only the paragraph number.

    Example:
    '1. Challenge...' becomes
    'Challenge...'
    """
    return re.sub(
        r"^\d{1,3}\.\s+",
        "",
        line
    ).strip()


def detect_heading(line):
    """
    Detect explicit legal headings.
    """

    cleaned = normalize_line(line)

    if not cleaned:
        return None

    upper = cleaned.upper()

    if upper in KNOWN_HEADINGS:
        return KNOWN_HEADINGS[upper]

    without_colon = upper.rstrip(":")

    if without_colon in KNOWN_HEADINGS:
        return KNOWN_HEADINGS[without_colon]

    return None


def looks_like_signature(line):
    """
    Detect common judicial signature patterns.
    """

    upper = line.upper()

    if "JUDGE" in upper and len(line) < 100:
        return True

    if re.match(
        r"^\(.+\)\s+\(.+\)$",
        line
    ):
        return True

    return False


def looks_like_certification(line):
    """
    Detect document-certification metadata.
    """

    lower = line.lower()

    certification_phrases = [
        "whether speaking/reasoned",
        "whether reportable",
        "i attest to the accuracy",
        "integrity of this document",
    ]

    return any(
        phrase in lower
        for phrase in certification_phrases
    )


def looks_like_order_paragraph(line):
    """
    Determine whether a NUMBERED paragraph is likely
    to contain the final decision/order.

    Important:
    We only call this on numbered paragraphs.

    This prevents a continuation line such as:
    'accordingly, if so advised.'
    from incorrectly starting the Order section.
    """

    lower = line.lower()

    strong_phrases = [
        "the petition is disposed",
        "the petition is allowed",
        "the petition is dismissed",
        "the appeal is allowed",
        "the appeal is dismissed",
        "the application is allowed",
        "the application is dismissed",
        "the present writ petition is disposed",
        "all the pending applications",
    ]

    return any(
        phrase in lower
        for phrase in strong_phrases
    )


def clean_text_lines(text):
    """
    Clean raw OCR text while preserving line boundaries.
    """

    result = []

    for raw_line in text.splitlines():

        line = normalize_line(raw_line)

        if not line:
            continue

        # Remove artificial OCR page markers
        if is_page_marker(line):
            continue

        result.append(line)

    return result


def create_paragraph(number, lines, page_start, page_end):
    """
    Create structured paragraph object.
    """

    text = " ".join(
        line.strip()
        for line in lines
        if line.strip()
    )

    return {
        "number": number,
        "text": text,
        "page_start": page_start,
        "page_end": page_end,
    }


def split_court_order(text):
    """
    Main court-order section splitting engine.

    The parser preserves the original legal wording
    and organizes it into structured sections.
    """

    lines = clean_text_lines(text)

    if not lines:
        return {
            "sections": []
        }

    sections = []

    current_section_id = "case_details"
    current_title = "Case Details"

    current_text_lines = []
    current_paragraphs = []

    current_paragraph_number = None
    current_paragraph_lines = []

    current_page = 1
    section_page_start = 1
    section_page_end = 1

    paragraph_page_start = 1
    paragraph_page_end = 1

    order_started = False
    signatures_started = False
    certification_started = False

    def flush_paragraph():
        nonlocal current_paragraph_number
        nonlocal current_paragraph_lines
        nonlocal paragraph_page_start
        nonlocal paragraph_page_end

        if current_paragraph_number is not None:

            paragraph = create_paragraph(
                current_paragraph_number,
                current_paragraph_lines,
                paragraph_page_start,
                paragraph_page_end
            )

            current_paragraphs.append(paragraph)

        current_paragraph_number = None
        current_paragraph_lines = []

    def flush_section():
        nonlocal current_text_lines
        nonlocal current_paragraphs

        flush_paragraph()

        if not current_text_lines and not current_paragraphs:
            return

        section = {
            "section_id": current_section_id,
            "title": current_title,
            "page_start": section_page_start,
            "page_end": section_page_end,
        }

        if current_paragraphs:
            section["paragraphs"] = current_paragraphs

        if current_text_lines:
            section["text"] = "\n".join(
                current_text_lines
            ).strip()

        sections.append(section)

        current_text_lines = []
        current_paragraphs = []

    for line in lines:

        # ------------------------------------------------
        # PAGE DETECTION
        # ------------------------------------------------

        page_number = get_page_number(line)

        if page_number is not None:
            current_page = page_number
            continue

        # ------------------------------------------------
        # CERTIFICATION
        # ------------------------------------------------

        if looks_like_certification(line):

            flush_section()

            current_section_id = "certification"
            current_title = "Document Certification"

            section_page_start = current_page
            section_page_end = current_page

            certification_started = True

            current_text_lines.append(line)

            continue

        # ------------------------------------------------
        # SIGNATURES
        # ------------------------------------------------

        if looks_like_signature(line):

            if not signatures_started:

                flush_section()

                current_section_id = "signatures"
                current_title = "Signatures"

                section_page_start = current_page
                section_page_end = current_page

                signatures_started = True

            current_text_lines.append(line)
            section_page_end = current_page

            continue

        # ------------------------------------------------
        # EXPLICIT HEADING
        # ------------------------------------------------

        heading = detect_heading(line)

        if heading:

            flush_section()

            current_section_id = (
                heading.lower()
                .replace(" ", "_")
                .replace("/", "_")
            )

            current_title = heading

            section_page_start = current_page
            section_page_end = current_page

            current_text_lines.append(line)

            continue

        # ------------------------------------------------
        # NUMBERED PARAGRAPH
        # ------------------------------------------------

        if is_numbered_paragraph(line):

            paragraph_number = get_paragraph_number(line)

            # Finish previous paragraph
            flush_paragraph()

            # Detect final order section.
            #
            # IMPORTANT:
            # This is checked only on a numbered paragraph.
            #
            if (
                not order_started
                and looks_like_order_paragraph(line)
            ):

                flush_section()

                current_section_id = "order"
                current_title = "Order"

                section_page_start = current_page
                section_page_end = current_page

                order_started = True

            elif (
                not order_started
                and current_section_id == "case_details"
            ):

                # First numbered paragraph means
                # we're leaving document metadata.
                flush_section()

                current_section_id = "proceedings"
                current_title = "Proceedings and Discussion"

                section_page_start = current_page
                section_page_end = current_page

            current_paragraph_number = paragraph_number
            current_paragraph_lines = [
                remove_paragraph_number(line)
            ]

            paragraph_page_start = current_page
            paragraph_page_end = current_page

            section_page_end = current_page

            continue

        # ------------------------------------------------
        # CONTINUATION OF CURRENT PARAGRAPH
        # ------------------------------------------------

        if current_paragraph_number is not None:

            current_paragraph_lines.append(line)
            paragraph_page_end = current_page
            section_page_end = current_page

            continue

        # ------------------------------------------------
        # NORMAL NON-PARAGRAPH TEXT
        # ------------------------------------------------

        current_text_lines.append(line)
        section_page_end = current_page

    # Finish everything
    flush_section()

    return {
        "sections": sections
    }


def split_court_order_file(
    input_file,
    output_file
):
    """
    Read OCR text and write structured JSON.
    """

    with open(
        input_file,
        "r",
        encoding="utf-8"
    ) as f:

        text = f.read()

    result = split_court_order(text)

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            result,
            f,
            ensure_ascii=False,
            indent=2
        )

    return result


def print_summary(result):
    """
    Print a concise human-readable summary.
    """

    sections = result.get("sections", [])

    print(
        f"Successfully created "
        f"{len(sections)} section(s)."
    )

    for section in sections:

        print(
            f"\n--- {section['title']} "
            f"({section['section_id']}) ---"
        )

        print(
            f"Pages: "
            f"{section.get('page_start')} - "
            f"{section.get('page_end')}"
        )

        paragraphs = section.get(
            "paragraphs",
            []
        )

        if paragraphs:

            print(
                f"Paragraphs: "
                f"{len(paragraphs)}"
            )

            for paragraph in paragraphs:

                preview = paragraph["text"]

                if len(preview) > 180:
                    preview = preview[:180] + "..."

                print(
                    f"  {paragraph['number']}. "
                    f"{preview}"
                )

        elif section.get("text"):

            preview = section["text"]

            if len(preview) > 500:
                preview = preview[:500] + "..."

            print(preview)


if __name__ == "__main__":

    if len(sys.argv) < 2:

        print(
            "Usage: "
            "python3 court_order_section_splitter.py "
            "<input_txt> [output_json]"
        )

        sys.exit(1)

    input_file = sys.argv[1]

    if len(sys.argv) >= 3:
        output_file = sys.argv[2]
    else:
        output_file = "court_order_sections.json"

    try:

        result = split_court_order_file(
            input_file,
            output_file
        )

        print_summary(result)

        print(
            f"\nOutput saved to: "
            f"{output_file}"
        )

    except FileNotFoundError:

        print(
            f"Input file not found: "
            f"{input_file}"
        )

        sys.exit(1)

    except Exception as e:

        print(
            f"Unable to split court order: {e}"
        )

        sys.exit(1)

import json
import sys


# Common explicit section headings found in court documents.
KNOWN_HEADINGS = {
    "FACTS": "Facts",
    "BRIEF FACTS": "Facts",
    "FACTUAL BACKGROUND": "Facts",
    "BACKGROUND": "Background",
    "ARGUMENTS": "Arguments",
    "SUBMISSIONS": "Submissions",
    "CONTENTIONS": "Contentions",
    "DISCUSSION": "Discussion",
    "FINDINGS": "Findings",
    "REASONS": "Reasons",
    "JUDGMENT": "Judgment",
    "ORDER": "Order",
    "OPERATIVE ORDER": "Order",
    "DIRECTIONS": "Directions",
    "CONCLUSION": "Conclusion",
}


# Words/phrases that commonly indicate the decision/order portion.
ORDER_INDICATORS = [
    "the petition is disposed",
    "the petition is allowed",
    "the petition is dismissed",
    "the appeal is allowed",
    "the appeal is dismissed",
    "the application is allowed",
    "the application is dismissed",
    "disposed of",
    "accordingly",
    "ordered accordingly",
]


def normalize_line(line: str) -> str:
    """
    Normalize whitespace while preserving the actual text.
    """
    return re.sub(r"\s+", " ", line).strip()


def is_numbered_paragraph(line: str) -> bool:
    """
    Detect paragraphs such as:
    1. ...
    2. ...
    10. ...
    """
    return bool(re.match(r"^\d{1,3}\.\s+", line))


def get_paragraph_number(line: str):
    """
    Return the paragraph number if present.
    """
    match = re.match(r"^(\d{1,3})\.\s+", line)
    if match:
        return int(match.group(1))
    return None


def detect_heading(line: str):
    """
    Detect known court-order headings.

    Returns the normalized heading name or None.
    """
    cleaned = normalize_line(line)

    if not cleaned:
        return None

    upper = cleaned.upper()

    # Exact known heading
    if upper in KNOWN_HEADINGS:
        return KNOWN_HEADINGS[upper]

    # Heading with a trailing colon
    if upper.rstrip(":") in KNOWN_HEADINGS:
        return KNOWN_HEADINGS[upper.rstrip(":")]

    return None


def looks_like_signature(line: str) -> bool:
    """
    Detect common signature lines such as:
    (LISA GILL) (SUDEEPTI SHARMA)
    JUDGE JUDGE
    """
    upper = line.upper()

    if "JUDGE" in upper and len(line) < 100:
        return True

    if re.match(r"^\(.+\)\s+\(.+\)$", line):
        return True

    return False


def looks_like_order_paragraph(text: str) -> bool:
    """
    Detect language that commonly occurs in the final decision/order.
    """
    lower = text.lower()

    return any(
        indicator in lower
        for indicator in ORDER_INDICATORS
    )


def clean_lines(text: str):
    """
    Convert raw extracted/OCR text into clean non-empty lines.
    """
    lines = []

    for raw_line in text.splitlines():
        line = normalize_line(raw_line)

        if line:
            lines.append(line)

    return lines


def split_court_order(text: str):
    """
    Split a court order into meaningful sections.

    Strategy:
    1. Detect explicit headings.
    2. Detect case metadata/header.
    3. Detect numbered legal paragraphs.
    4. Detect decision/order portion.
    5. Detect signatures.
    6. Preserve all original text.
    """

    lines = clean_lines(text)

    if not lines:
        return {
            "sections": []
        }

    sections = []

    current_title = "Case Details"
    current_id = "case_details"
    current_lines = []

    saw_numbered_paragraph = False
    order_started = False
    signatures_started = False

    def flush_section():
        nonlocal current_lines

        if current_lines:
            section_text = "\n".join(current_lines).strip()

            if section_text:
                sections.append({
                    "section_id": current_id,
                    "title": current_title,
                    "text": section_text
                })

        current_lines = []

    for line in lines:

        # -------------------------------------------------
        # 1. Signature detection
        # -------------------------------------------------
        if looks_like_signature(line):
            if not signatures_started:
                flush_section()

                current_id = "signatures"
                current_title = "Signatures"
                signatures_started = True

            current_lines.append(line)
            continue

        # -------------------------------------------------
        # 2. Explicit heading detection
        # -------------------------------------------------
        heading = detect_heading(line)

        if heading:
            flush_section()

            normalized_id = heading.lower().replace(" ", "_").replace("/", "_")

            current_id = normalized_id
            current_title = heading

            current_lines.append(line)
            continue

        # -------------------------------------------------
        # 3. Numbered paragraphs
        # -------------------------------------------------
        if is_numbered_paragraph(line):

            paragraph_number = get_paragraph_number(line)
            saw_numbered_paragraph = True

            # Once we detect a paragraph containing
            # a strong order indicator, start the Order section.
            if not order_started and looks_like_order_paragraph(line):
                flush_section()

                current_id = "order"
                current_title = "Order"

                order_started = True

            # If we have already reached the order section,
            # continue adding numbered paragraphs there.
            current_lines.append(line)
            continue

        # -------------------------------------------------
        # 4. If an order has not explicitly started,
        #    inspect ordinary lines for order indicators.
        # -------------------------------------------------
        if not order_started and looks_like_order_paragraph(line):
            flush_section()

            current_id = "order"
            current_title = "Order"

            order_started = True

        # -------------------------------------------------
        # 5. Normal text
        # -------------------------------------------------
        current_lines.append(line)

    # Flush final section
    flush_section()

    return {
        "sections": sections
    }


def split_court_order_file(input_file: str, output_file: str):
    """
    Read text from a file and save structured sections as JSON.
    """

    with open(input_file, "r", encoding="utf-8") as f:
        text = f.read()

    result = split_court_order(text)

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(
            result,
            f,
            ensure_ascii=False,
            indent=2
        )

    return result


if __name__ == "__main__":

    if len(sys.argv) < 2:
        print(
            "Usage: python court_order_section_splitter.py "
            "<input_txt> [output_json]"
        )
        sys.exit(1)

    input_file = sys.argv[1]

    if len(sys.argv) >= 3:
        output_file = sys.argv[2]
    else:
        output_file = "court_order_sections.json"

    try:
        result = split_court_order_file(
            input_file,
            output_file
        )

        print(
            f"Successfully created {len(result['sections'])} section(s)."
        )

        print(f"Output saved to: {output_file}")

        for section in result["sections"]:
            print(
                f"\n--- {section['title']} "
                f"({section['section_id']}) ---"
            )

            print(section["text"][:500])

    except FileNotFoundError:
        print(f"Input file not found: {input_file}")
        sys.exit(1)

    except Exception as e:
        print(f"Unable to split court order: {e}")
        sys.exit(1)
