"""Secure storage for lawyer verification documents (Phase 2b).

Design rules (the brief, enforced here rather than by convention):

* **type** — a file is accepted only when magic bytes, filename
  extension AND (when supplied) content-type all say PDF, JPEG or
  PNG; a spoofed extension or header never reaches disk;
* **size** — hard 10 MB cap, checked before anything else runs
  (matches the NLP service's upload policy);
* **never executed** — bytes are written outside any web root: the
  app serves no static files at all, the only way to read a
  document back is an authenticated endpoint, the on-disk name is
  generated by the server (no user input in any path — path
  traversal has nothing to traverse), files are opened with mode
  0600 and returned as ``Content-Disposition: attachment`` with
  ``X-Content-Type-Options: nosniff``;
* **not public** — nothing is mounted, listed, or guessable;
  ``GET /api/admin/lawyers/{id}/document`` is ADMIN-only and
  ``GET /api/auth/lawyer/verification-document`` returns only the
  caller's own file;
* **one copy** — the row is keyed by ``lawyer_id``; a re-upload
  deletes the previous file first, so no stale duplicates
  accumulate.

No new packages: everything here is stdlib (``hashlib``,
``secrets``, ``pathlib``, ``re``).
"""

from __future__ import annotations

import hashlib
import os
import re
import secrets
from pathlib import Path

from database.sqlite_db import get_db_path

MAX_DOCUMENT_BYTES = 10 * 1024 * 1024

# extension -> canonical MIME
ALLOWED_TYPES: dict[str, str] = {
    ".pdf": "application/pdf",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
}

# Content-types browsers/Postman may legitimately send for these
# families. ``application/octet-stream`` is tolerated because the
# magic bytes below are still verified; anything else is refused.
ALLOWED_CONTENT_TYPES = {
    "application/pdf",
    "image/jpeg",
    "image/jpg",
    "image/png",
    "application/octet-stream",
    "",
}

_MAGIC_PREFIXES: dict[str, bytes] = {
    ".pdf": b"%PDF-",
    ".jpg": b"\xff\xd8\xff",
    ".jpeg": b"\xff\xd8\xff",
    ".png": b"\x89PNG\r\n\x1a\n",
}

_SAFE_NAME = re.compile(r"[^A-Za-z0-9._ -]+")
_STORED_NAME = re.compile(
    r"^[A-Za-z0-9_-]{1,60}-[0-9a-f]{16}\.(pdf|jpg|jpeg|png)$"
)


def uploads_root() -> Path:
    """Where documents live — next to the auth database file.

    Deriving the directory from ``NYAYMITRA_AUTH_DB`` is what keeps
    tests hermetic: pointing the env var at a throwaway path also
    points its uploads there, and the development database's files
    stay under ``data/uploads/verification``.
    """
    return Path(get_db_path()).parent / "uploads" / "verification"


def sanitize_filename(raw: str | None) -> str:
    """A display name that cannot carry a path or shell surprises.

    Strips every directory component, replaces unsafe characters,
    collapses runs of dots, and caps the length. This string is
    stored for humans to read — it is never used to build a path.
    """
    base = (raw or "").replace("\\", "/").rsplit("/", 1)[-1]
    cleaned = _SAFE_NAME.sub("_", base).strip(" .")
    cleaned = re.sub(r"\.{2,}", ".", cleaned)
    cleaned = re.sub(r"_{2,}", "_", cleaned)

    if not cleaned or cleaned in {".", ".."}:
        return "document"

    if len(cleaned) > 120:
        stem, dot, ext = cleaned.rpartition(".")
        if dot and len(ext) <= 10:
            cleaned = stem[: 120 - len(ext) - 1] + "." + ext
        else:
            cleaned = cleaned[:120]

    return cleaned


def detect_type(
    data: bytes,
    filename: str | None,
    content_type: str | None,
) -> tuple[str, str] | None:
    """Return ``(extension, canonical_mime)`` or ``None``.

    The magic bytes are authoritative; the extension must belong to
    the same family; a declared content-type must be one we expect.
    Three independent signals must agree — one spoofed field buys
    nothing.
    """
    if not data:
        return None

    header = (content_type or "").split(";")[0].strip().lower()
    if header not in ALLOWED_CONTENT_TYPES:
        return None

    suffix = Path(sanitize_filename(filename)).suffix.lower()
    if suffix not in ALLOWED_TYPES:
        return None

    magic = _MAGIC_PREFIXES[suffix]
    if not data.startswith(magic):
        return None

    return suffix, ALLOWED_TYPES[suffix]


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def stored_name(lawyer_id: str, extension: str) -> str:
    """Server-generated on-disk name: id + random hex + extension.

    The lawyer id comes from our own database (``LAWYER_NNNN``) and
    is still stripped to a safe charset; the random suffix makes the
    path unguessable and collision-free.
    """
    safe_id = re.sub(r"[^A-Za-z0-9_-]", "", lawyer_id)[:60] or "lawyer"
    return f"{safe_id}-{secrets.token_hex(8)}{extension}"


def save_document(lawyer_id: str, data: bytes, extension: str) -> str:
    """Write one file, exclusive-create, mode 0600. Returns its name."""
    root = uploads_root()
    root.mkdir(parents=True, exist_ok=True)

    name = stored_name(lawyer_id, extension)
    path = root / name

    # O_EXCL: never fall back to overwriting somebody's file.
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "wb") as handle:
        handle.write(data)

    try:
        os.chmod(path, 0o600)
    except OSError:  # pragma: no cover - platform dependent
        pass

    return name


def document_path(stored: str) -> Path | None:
    """Resolve a stored name, refusing anything that escapes root."""
    if not _STORED_NAME.fullmatch(stored or ""):
        return None

    root = uploads_root().resolve()
    path = (root / stored).resolve()

    if path.parent != root:
        return None

    return path


def delete_document(stored: str | None) -> None:
    """Best-effort removal of the previous copy."""
    if not stored:
        return

    path = document_path(stored)
    if path is None:
        return

    try:
        path.unlink()
    except FileNotFoundError:
        pass
    except OSError:  # pragma: no cover - platform dependent
        pass
